language: php
php:
  - '7.3'

addons:
  sonarcloud:
    organization: "kreait"

git:
  depth: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

before_install: .travis/before_install.sh

install: .travis/install.sh

script: .travis/build.sh

notifications:
  email:
    - secure: "iiseqb4k4ckQkMJnZ6Tq3YP5ilTZE4CkVgarsBpPOn+c820nP9QokGpz82D4CTGy/UB1+DfCiFH9YAFrhLP5/9Go1CHP+wYkuz9W+E8q/rm9/nBO0xutoQhOfV3MxMid69E8i4QjODq3w5mOUrmpj/8gl2FyBU1Ro1xgPSYNEQ4="
